BOARD_WIDTH = 20
BOARD_HEIGHT = 20
CELL_SIZE = 30


HUMAN_STRENGTH = 5 
HUMAN_INITIATIVE = 4
WOLF_STRENGTH = 9 
WOLF_INITIATIVE = 5
SHEEP_STRENGTH = 4 
SHEEP_INITIATIVE = 4
FOX_STRENGTH = 3 
FOX_INITIATIVE = 7 
TURTLE_STRENGTH = 2 
TURTLE_INITIATIVE = 1
ANTELOPE_STRENGTH = 4 
ANTELOPE_INITIATIVE = 4
CYBER_STRENGTH = 6
CYBER_INITIATIVE = 6

PLANTS_INITIATIVE = 0
GRASS_STRENGTH = 0
SOW_STRENGTH = 0
GUARANA_STRENGTH = 0
BELLADONA_STRENGTH = 99
SOSNOWSKY_STRENGTH = 10

SOSNOWSKY_X = 15
SOSNOWSKY_Y = 15

CHANCE_TO_BREED = 0.2
CHANCE_TO_SPREAD = 0.1
